// Isolated PostgreSQL only; no remote connection, real season or real ESPN calls.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { fixtureSeeds } from '../../lib/playoffs/roundFixtures.mjs';
import { expectedMatchups } from '../../lib/playoffs/rounds.mjs';

test('round migration and protected atomic operations in isolated PostgreSQL',{skip:!process.env.PGLITE_MODULE},async t=>{
 const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE).href);
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
   create table public.playoff_rounds(id bigint generated by default as identity primary key,season integer not null,round_key text not null,round_name text not null,round_order integer not null,status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(season,round_key),unique(season,round_order),check(status in ('draft','open','locked','scored','finalized')));
   create table public.playoff_games(id bigint generated by default as identity primary key,round_id bigint not null references public.playoff_rounds(id),external_game_id text unique,game_date timestamptz not null,away_team text not null,home_team text not null,away_score integer,home_score integer,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
   alter table public.playoff_rounds enable row level security;alter table public.playoff_games enable row level security;
   grant select on public.playoff_rounds,public.playoff_games to authenticated,service_role;
   create policy rounds_read on public.playoff_rounds for select to authenticated using(true);
   create policy games_read on public.playoff_games for select to authenticated using(true);`);
  await db.exec(await readFile(new URL('../migrations/202609240001_playoff_seeds.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../migrations/202609250001_playoff_round_admin.sql',import.meta.url),'utf8'));
  const seeds=fixtureSeeds();
  await db.query('select public.sync_playoff_seeds(2099,$1::jsonb)',[JSON.stringify(seeds)]);
  const snapshot=async()=> (await db.query(`select jsonb_build_object('rounds',coalesce((select jsonb_agg(to_jsonb(r)) from public.playoff_rounds r where season=2099),'[]'),'games',coalesce((select jsonb_agg(to_jsonb(g)) from public.playoff_games g join public.playoff_rounds r on r.id=g.round_id where r.season=2099),'[]')) as data`)).rows[0].data;
  const run=async(action,key,games,expected)=>db.query('select public.manage_playoff_round(2099,$1,$2,$3::jsonb,$4::jsonb)',[action,key,JSON.stringify(games),JSON.stringify(expected ?? await snapshot())]);
  const gamesFor=(pairs,base)=>pairs.map((p,i)=>({...p,external_game_id:String(base+i),game_date:'2100-01-10T18:00:00Z'}));
  const wc=gamesFor(expectedMatchups(seeds,2099,'wild_card',[],[]),900);
  await t.test('provisional snapshot refuses all round writes',async()=>{
   await assert.rejects(run('prepare','wild_card',wc),/Finalized seeds/);assert.equal((await snapshot()).rounds.length,0);
  });
  await db.exec('select public.finalize_playoff_seeds(2099,(select captured_at from public.playoff_seeds limit 1))');
  await t.test('authenticated and anon cannot execute RPC or modify games',async()=>{
   for(const role of ['authenticated','anon']){
    const prior=await snapshot();await db.exec(`set role ${role}`);
    await assert.rejects(run('prepare','wild_card',wc,prior),/permission denied/);
    await assert.rejects(db.exec('delete from public.playoff_games'),/permission denied/);await db.exec('reset role');
   }
  });
  const initial=await snapshot();
  await t.test('complete prepare atomically creates exactly six games; stale retry creates no duplicate',async()=>{
   await db.exec('set role service_role');await run('prepare','wild_card',wc,initial);await db.exec('reset role');
   const state=await snapshot();assert.equal(state.games.length,6);assert.equal(state.rounds[0].status,'open');
   await assert.rejects(run('prepare','wild_card',wc,initial),/Stale rounds/);assert.equal((await snapshot()).games.length,6);
  });
  await t.test('incomplete/invalid updates roll back every score; stale results cannot overwrite',async()=>{
   const before=await snapshot();
   const updates=before.games.map(g=>({id:g.id,external_game_id:g.external_game_id,game_status:'post',home_score:17,away_score:24}));
   const broken=structuredClone(updates);broken.at(-1).home_score=24;
   await assert.rejects(run('update','wild_card',broken));assert.deepEqual(await snapshot(),before);
   await run('update','wild_card',updates);
   await assert.rejects(run('update','wild_card',updates,before),/Stale/);
   assert.equal((await snapshot()).rounds[0].status,'locked');
  });
  await t.test('missing next matchup refuses transition and keeps source locked',async()=>{
   const before=await snapshot();const div=gamesFor(expectedMatchups(seeds,2099,'divisional',before.rounds,before.games),1000);
   await assert.rejects(run('advance','wild_card',div.slice(1)),/Incomplete/);assert.deepEqual(await snapshot(),before);
   // A failure after inserts have begun must roll back new round and all games.
   await db.exec(`create function public.reject_test_game() returns trigger language plpgsql as $$begin if new.external_game_id='1003' then raise exception 'Injected test failure';end if;return new;end;$$;
     create trigger reject_test_game before insert on public.playoff_games for each row execute function public.reject_test_game();`);
   await assert.rejects(run('advance','wild_card',div),/Injected/);assert.deepEqual(await snapshot(),before);
   await db.exec('drop trigger reject_test_game on public.playoff_games;drop function public.reject_test_game()');
   await run('advance','wild_card',div);
   const after=await snapshot();assert.equal(after.games.length,10);assert.equal(after.rounds.find(r=>r.round_key==='wild_card').status,'finalized');assert.equal(after.rounds.find(r=>r.round_key==='divisional').status,'open');
  });
  await t.test('full progression opens 2 conference games then 1 ESPN-oriented Super Bowl, never a fifth round',async()=>{
   for(const [key,next,base] of [['divisional','conference',1100],['conference','super_bowl',1200]]){
    let state=await snapshot();const source=state.rounds.find(r=>r.round_key===key);
    const updates=state.games.filter(g=>g.round_id===source.id).map(g=>({id:g.id,external_game_id:g.external_game_id,game_status:'post',home_score:17,away_score:24}));
    await run('update',key,updates);state=await snapshot();
    let pairs=expectedMatchups(seeds,2099,next,state.rounds,state.games);
    if(next==='super_bowl')pairs=pairs.map(p=>({home_team:p.away_team,away_team:p.home_team}));
    await run('advance',key,gamesFor(pairs,base));
   }
   const state=await snapshot();assert.equal(state.games.length,13);assert.equal(state.rounds.length,4);
   const sb=state.rounds.find(r=>r.round_key==='super_bowl');assert.equal(state.games.find(g=>g.round_id===sb.id).home_team,'NFC7');
   await assert.rejects(run('advance','super_bowl',[]),/final round/);assert.deepEqual(await snapshot(),state);
  });
 }finally{await db.close();}
});
