import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {expectedMatchups} from '../../lib/playoffs/rounds.mjs';
import {scoringFixture} from '../../lib/playoffs/scoringFixtures.mjs';
import {completeUpdate} from '../../lib/playoffs/scoringOperations.mjs';
import {processedPlayoffResults} from '../../app/series/components/public-pages/processedResults.mjs';
import {calculateRound} from '../../lib/playoffs/scoring.mjs';
const user='00000000-0000-0000-0000-000000000001';
test('scoring migration and atomic lifecycle in isolated PostgreSQL',{skip:!process.env.PGLITE_MODULE},async t=>{
 const {PGlite}=await import(pathToFileURL(process.env.PGLITE_MODULE).href);const db=new PGlite();
 try {
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table public.users(id uuid primary key);insert into public.users values('${user}');
 create table public.teams(name text primary key,espn_abbr text);insert into public.teams values('A','AAA'),('B','BBB');
 create table public.qbs(id bigint primary key,name text,team text,is_active_starter boolean,espn_athlete_id text,active boolean default true);insert into public.qbs values(1,'Starter','A',true,'10',true),(2,'Backup','B',true,'20',true);
 create table public.playoff_rounds(id bigint generated by default as identity primary key,season integer not null,round_key text not null,round_name text not null,round_order integer not null,status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(season,round_key),unique(season,round_order),check(status in('draft','open','locked','scored','finalized')));
 create table public.playoff_games(id bigint generated by default as identity primary key,round_id bigint references public.playoff_rounds(id),external_game_id text unique,game_date timestamptz not null,home_team text not null,away_team text not null,home_score integer,away_score integer,created_at timestamptz default now(),updated_at timestamptz default now());
 create table public.playoff_picks(id bigint generated by default as identity primary key,user_id uuid references public.users(id),game_id bigint references public.playoff_games(id),picked_team text,predicted_spread integer,unique(user_id,game_id));
 create table public.playoff_qb_picks(id bigint generated by default as identity primary key,user_id uuid references public.users(id),round_id bigint references public.playoff_rounds(id),qb_id bigint references public.qbs(id),unique(user_id,round_id));
 create table public.playoff_team_paths(id bigint generated by default as identity primary key,user_id uuid references public.users(id),round_id bigint references public.playoff_rounds(id),team text,multiplier integer,continues_previous_path boolean,unique(user_id,round_id));
 grant all on public.playoff_picks,public.playoff_qb_picks,public.playoff_team_paths to authenticated;`);
 for(const file of ['202609240001_playoff_seeds.sql','202609250001_playoff_round_admin.sql','202609290001_playoff_scoring.sql'])await db.exec(await readFile(new URL('../migrations/'+file,import.meta.url),'utf8'));
 await t.test('new migration can be reapplied without replaying earlier migrations',async()=>await db.exec(await readFile(new URL('../migrations/202609290001_playoff_scoring.sql',import.meta.url),'utf8')));
 await db.exec(`create table push_notification_events(event_key text primary key,user_id uuid,notification_type text,week integer,scheduled_for timestamptz,status text,sent_at timestamptz);
 create table settings(current_week integer);create table qb_selection_weeks(week integer,started_at timestamptz);
 create table qb_picks(week integer,user_id uuid);create table games(week integer,is_pool_eligible boolean,game_date timestamptz);`);
 await db.exec(await readFile(new URL('../migrations/202609300001_notification_reminders.sql',import.meta.url),'utf8'));
 await db.exec(`insert into public.playoff_rounds(season,round_key,round_name,round_order,status) values(2099,'wild_card','Wild Card',1,'open');
 insert into public.playoff_games(round_id,external_game_id,game_date,home_team,away_team,game_status) values(1,'TEST-WC','2100-01-01','A','B','pre');`);
 const snapshot=async()=>(await db.query('select public.playoff_scoring_state(2099) as state')).rows[0].state;
 const submit=()=>db.query('select public.submit_playoff_round(1,1,$1,$2::jsonb)',['A',JSON.stringify([{game_id:1,picked_team:'A',predicted_spread:7}])]);
 await t.test('JWT submission is complete, atomic and once-only; direct writes revoked',async()=>{
  await assert.rejects(submit(),/Authentication/);
  await db.exec(`set request.jwt.claim.sub='${user}';set role authenticated;`);
  await assert.rejects(db.exec('insert into public.playoff_qb_picks(user_id,round_id,qb_id) values(null,1,1)'),/permission denied/);
  await submit();await assert.rejects(submit(),/already exists/);await db.exec('reset role');
  const state=await snapshot();assert.equal(state.picks.length,1);assert.equal(state.paths.length,1);assert.equal(state.qbPicks.length,1);
 });
 const publish=async(publication,expected,action='update',updates=[])=>db.query('select public.publish_playoff_scoring(2099,1,$1,$2::jsonb,$3::jsonb,$4::jsonb)',[action,JSON.stringify(expected??await snapshot()),JSON.stringify(updates),publication===null?null:JSON.stringify(publication)]);
 const calculate=state=>calculateRound({round:state.rounds[0],games:state.games,picks:state.picks,qbPicks:state.qbPicks,paths:state.paths,qbs:state.qbs,seeds:[],qbResults:{[user]:{selected_qb_id:1,actual_espn_athlete_id:'10',actual_qb_name:'Starter',team:'A',passer_rating:120,consumed:true,dnp:false,game_id:1}}});
 await t.test('non-final cannot publish, TEST cannot be overwritten via ESPN payload',async()=>{
  await assert.rejects(publish({results:[],standings:[]}),/FINAL/);
  await assert.rejects(publish(null,undefined,'update',[{id:1,external_game_id:'TEST-WC',game_status:'post',home_score:24,away_score:17}]),/TEST/);
  assert.equal((await snapshot()).games[0].game_status,'pre');
 });
 await db.exec("update public.playoff_games set game_status='post',home_score=24,away_score=17 where id=1");
 await t.test('publication atomic, idempotent replacement and stale concurrency rejection',async()=>{
  let state=await snapshot(),result=calculate(state);await publish(result,state);
  await assert.rejects(publish(result,state),/Stale/);
  state=await snapshot();await publish(calculate(state),state);
  assert.equal((await snapshot()).results.length,1);assert.equal((await snapshot()).runs.length,1);
  assert.equal((await snapshot()).results[0].final_score,2.4);
  const broken=calculate(await snapshot());broken.results[0].final_score=999;const before=await snapshot();
  await assert.rejects(publish(broken,before),/check constraint/);assert.deepEqual(await snapshot(),before);
 });
 await t.test('new inputs require recalculation; corrections replace totals and ranks',async()=>{
  await db.exec('update public.playoff_games set home_score=25 where id=1');
  await assert.rejects(publish(null,undefined,'finalize'),/current publication/);
  await publish(calculate(await snapshot()));assert.equal((await snapshot()).results[0].final_score,1.2);
 });
 await t.test('RLS/ACL exact grants; only service can read sources and write scoring',async()=>{
  const policies=(await db.query("select tablename from pg_policies where tablename in('playoff_round_runs','playoff_round_results')")).rows;assert.equal(policies.length,2);
  for(const role of ['anon','authenticated']){
   const state=await snapshot();await db.exec(`set role ${role}`);
   await assert.rejects(db.exec('select public.playoff_scoring_state(2099)'),/permission denied/);
   await assert.rejects(publish(null,state,'finalize'),/permission denied/);
   await assert.rejects(db.exec('delete from public.playoff_round_results'),/permission denied/);
   await assert.rejects(db.exec('select source from public.playoff_round_runs'),/permission denied/);
   if(role==='authenticated'){assert.equal((await db.query('select * from public.playoff_round_results')).rows.length,1);assert.equal((await db.query('select public.read_playoff_results(array[1]::bigint[]) as data')).rows[0].data.runs.length,1);}
   else await assert.rejects(db.exec('select * from public.playoff_round_results'),/permission denied/);
   await db.exec('reset role');
  }
 });
 await t.test('explicit finalization locks games, choices, publication and round against direct privileged edits',async()=>{
  const state=await snapshot();await db.exec('set role service_role');await publish(null,state,'finalize');await db.exec('reset role');
  assert.equal((await snapshot()).rounds[0].status,'finalized');assert.ok((await snapshot()).runs[0].finalized_at);
  await assert.rejects(publish(null),/non-finalized/);
  for(const sql of ['update public.playoff_games set home_score=26 where id=1','delete from public.playoff_picks','delete from public.playoff_qb_picks','delete from public.playoff_team_paths','delete from public.playoff_round_results','delete from public.playoff_round_runs',"update public.playoff_rounds set status='locked' where id=1"])
   await assert.rejects(db.exec(sql),/immutable/);
 });
 await t.test('complete four-round TEST season through orchestration + SQL; bye, DNP, reset, cumulative snapshots',async()=>{
  const f=scoringFixture();
  for(const id of f.users)await db.query('insert into public.users values($1)',[id]);
  for(const seed of f.seeds)await db.query('insert into public.teams values($1,$1)',[seed.team]);
  for(const q of f.qbs)await db.query('insert into public.qbs values($1,$2,$3,true,$4,true)',[q.id,q.name,q.team,q.espn_athlete_id]);
  await db.query('select public.sync_playoff_seeds(2101,$1::jsonb)',[JSON.stringify(f.seeds)]);
  await db.exec('select public.finalize_playoff_seeds(2101,(select captured_at from public.playoff_seeds where season=2101 limit 1))');
  const client={async rpc(name,p){
    try {
      if(name==='playoff_scoring_state')return {data:(await db.query('select public.playoff_scoring_state($1) as data',[p.p_season])).rows[0].data};
      await db.query('select public.publish_playoff_scoring($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)',[p.p_season,p.p_round_id,p.p_action,JSON.stringify(p.p_expected),JSON.stringify(p.p_updates),p.p_publication===null?null:JSON.stringify(p.p_publication)]);
      return {error:null};
    }catch(error){return {error};}
  }};
  for(const [i,b] of f.batches.entries()){
    await db.query("insert into public.playoff_rounds(id,season,round_key,round_name,round_order,status) values($1,2101,$2,$3,$4,'open')",[b.round.id,b.round.round_key,b.round.round_name,i+1]);
    for(const g of b.games)await db.query("insert into public.playoff_games(id,round_id,external_game_id,game_date,home_team,away_team,game_status) values($1,$2,$3,$4,$5,$6,'pre')",[g.id,g.round_id,g.external_game_id,g.game_date,g.home_team,g.away_team]);
    for(const uid of f.users){
      await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);
      await db.exec('set role authenticated');
      const payload=JSON.stringify(b.picks.filter(p=>p.user_id===uid));
      const pathTeam=b.paths.find(p=>p.user_id===uid).team;
      if(i>0){
        await assert.rejects(db.query('select public.submit_playoff_round($1,100,$2,$3::jsonb,$4)',[b.round.id,pathTeam,payload,i===3?55:null]),/QB already used/);
        if(uid===f.users[0])await assert.rejects(db.query('select public.submit_playoff_round($1,$2,$3,$4::jsonb,$5)',[b.round.id,b.qbPicks[0].qb_id,'NFC1',payload,i===3?55:null]),/Surviving path/);
      }
      if(i===2){
        await db.exec('begin');
        try {await db.query('select public.submit_playoff_round($1,101,$2,$3::jsonb)',[b.round.id,pathTeam,payload]);}
        finally {await db.exec('rollback');}
      }
      if(i===3){
        for(const invalid of [null,-1])await assert.rejects(db.query('select public.submit_playoff_round($1,$2,$3,$4::jsonb,$5)',[b.round.id,b.qbPicks[0].qb_id,pathTeam,payload,invalid]),/Super Bowl total/);
      }else await assert.rejects(db.query('select public.submit_playoff_round($1,$2,$3,$4::jsonb,55)',[b.round.id,b.qbPicks[0].qb_id,pathTeam,payload]),/Super Bowl total/);
      await db.query('select public.submit_playoff_round($1,$2,$3,$4::jsonb,$5)',[b.round.id,b.qbPicks[0].qb_id,pathTeam,payload,i===3?55:null]);
      await db.exec('reset role');
    }
    for(const g of b.games)await db.query("update public.playoff_games set game_status='post',home_score=$1,away_score=$2,test_qb_results=$3::jsonb where id=$4",[g.home_score,g.away_score,JSON.stringify(g.test_qb_results),g.id]);
    const request={season:2101,roundKey:b.round.round_key};
    const update=await completeUpdate(client,request,()=>assert.fail('TEST must never fetch ESPN'));
    assert.deepEqual(update.warnings,[]);
    await completeUpdate(client,request,()=>assert.fail('TEST retry must never fetch ESPN'));
    let state=(await client.rpc('playoff_scoring_state',{p_season:2101})).data;
    const own=state.results.filter(s=>s.round_id===b.round.id);
    assert.ok(state.qbPicks.filter(q=>q.round_id===b.round.id).every(q=>q.super_bowl_total===(i===3?55:null)));
    assert.equal(own.length,3);assert.deepEqual(own.map(s=>s.path_multiplier),[i+1,[0,1,2,3][i],[1,2,3,1][i]]);
    if(i===1)assert.ok(own.every(s=>s.qb_consumed===false));
    const view=processedPlayoffResults({rounds:state.rounds,processed:state});assert.ok(view.progression.rows.every(row=>row.points.length===i+1));
    for(const row of own){const previous=state.results.filter(s=>s.user_id===row.user_id&&s.round_order<=i);assert.equal(row.cumulative_score,previous.reduce((n,s)=>n+s.final_score,0)+row.final_score);}
    await completeUpdate(client,{...request,action:'finalize'},()=>assert.fail('finalize does not fetch'));
    await assert.rejects(completeUpdate(client,request,()=>assert.fail('finalized never fetches')),/finalisée/);
  }
  const state=(await client.rpc('playoff_scoring_state',{p_season:2101})).data;
  assert.equal(state.games.length,13);assert.equal(state.runs.length,4);assert.equal(state.results.length,12);assert.ok(state.rounds.every(r=>r.status==='finalized'));
 });
 await t.test('official advance requires separate finalization and preserves its source snapshot',async()=>{
  const f=scoringFixture(2102);
  await db.query('select public.sync_playoff_seeds(2102,$1::jsonb)',[JSON.stringify(f.seeds)]);
  await db.exec('select public.finalize_playoff_seeds(2102,(select captured_at from public.playoff_seeds where season=2102 limit 1))');
  const state=async()=>(await db.query('select public.playoff_scoring_state(2102) as data')).rows[0].data;
  const manage=async(action,games)=>{const d=await state();return db.query('select public.manage_playoff_round(2102,$1,$2,$3::jsonb,$4::jsonb)',[action,'wild_card',JSON.stringify(games),JSON.stringify({rounds:d.rounds,games:d.games})]);};
  await manage('prepare',f.batches[0].games.map((g,i)=>({...g,external_game_id:String(50000+i)})));
  let d=await state(),r=d.rounds[0];
  const picks=d.games.map(g=>({game_id:g.id,picked_team:[g.home_team,g.away_team].includes('AFC7')?'AFC7':g.home_team,predicted_spread:7}));
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);
  await db.query('select public.submit_playoff_round($1,100,$2,$3::jsonb)',[r.id,'AFC7',JSON.stringify(picks)]);
  for(const g of d.games)await db.query("update public.playoff_games set game_status='post',home_score=$1,away_score=$2 where id=$3",[g.away_team==='AFC7'?17:24,g.away_team==='AFC7'?24:17,g.id]);
  d=await state();const next=expectedMatchups(d.seeds,2102,'divisional',d.rounds,d.games).map((g,i)=>({...g,external_game_id:String(60000+i),game_date:'2200-01-20T18:00:00Z'}));
  await assert.rejects(manage('advance',next),/FINAL/);
  // Emulate a legacy finalized row from the pre-scoring migration, then roll back.
  await db.exec('begin;alter table public.playoff_rounds disable trigger guard_finalized_playoff');
  await db.query("update public.playoff_rounds set status='finalized' where id=$1",[r.id]);
  await assert.rejects(manage('advance',next),/FINAL/);
  await db.exec('rollback');
  const publication=calculateRound({round:r,games:d.games,picks:d.picks,qbPicks:d.qbPicks,paths:d.paths,qbs:d.qbs,seeds:d.seeds,qbResults:{[user]:{selected_qb_id:100,actual_espn_athlete_id:'500',actual_qb_name:'Fixture QB',team:'AFC7',passer_rating:100,consumed:true,dnp:false,game_id:d.games[0].id}}});
  await db.query('select public.publish_playoff_scoring(2102,$1,$2,$3::jsonb,$4::jsonb,$5::jsonb)',[r.id,'update',JSON.stringify(d),'[]',JSON.stringify(publication)]);
  await assert.rejects(manage('advance',next),/FINAL/);
  d=await state();await db.query('select public.publish_playoff_scoring(2102,$1,$2,$3::jsonb,$4::jsonb,null)',[r.id,'finalize',JSON.stringify(d),'[]']);
  const before=await state();await manage('advance',next);const after=await state();
  assert.equal(after.rounds.find(r=>r.round_key==='divisional').status,'open');
  assert.deepEqual(after.rounds.find(row=>row.id===r.id),before.rounds[0]);assert.deepEqual(after.results,before.results);assert.deepEqual(after.runs,before.runs);
 });
 } finally {await db.close();}
});
