import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),swc=require('next/dist/build/swc');
test('actual lifecycle route authenticates admin and ignores browser calendars/actor',async()=>{
 const source=await readFile(new URL('../../app/api/admin/season-lifecycle/route.js',import.meta.url),'utf8');
 const {code}=await swc.transform(source,{filename:'route.js',jsc:{parser:{syntax:'ecmascript'}},module:{type:'commonjs'}});
 let isAdmin=true,logged=true,prepared=0;const calls=[];
 const context={current_season:2026,revision:7,phase:'offseason'};
 const client={auth:{getUser:async()=>({data:{user:logged?{id:'real-admin'}:null}})},from(table){const q={select(){return this;},eq(){return this;},single:async()=>({data:{is_admin:isAdmin}}),then(resolve){return Promise.resolve({data:[{name:'Bills',espn_abbr:'BUF'}]}).then(resolve);}};return q;},rpc:async(name,args)=>{calls.push({name,args});return {data:{action:args.p_action}};}};
 const exports={};new Function('require','exports',code)(id=>id==='@supabase/supabase-js'?{createClient:()=>client}:id.endsWith('context.mjs')?{loadLifecycle:async()=>context}:{prepareCalendar:async()=>{prepared++;return {games:[{external_game_id:'official'}]};}},exports);
 const request=(body,token='Bearer local')=>({headers:{get:()=>token},json:async()=>body});
 const body={action:'prepare',season:2027,revision:7,confirm:true,games:[{external_game_id:'browser'}],actor:'fake'};
 assert.equal((await exports.POST(request(body,null))).status,401);
 logged=false;assert.equal((await exports.POST(request(body))).status,401);logged=true;
 isAdmin=false;assert.equal((await exports.POST(request(body))).status,403);isAdmin=true;
 assert.equal((await exports.POST(request({...body,confirm:false}))).status,409);
 assert.equal((await exports.POST(request({...body,revision:6}))).status,409);assert.equal(prepared,0);assert.equal(calls.length,0);
 assert.equal((await exports.POST(request(body))).status,200);assert.equal(prepared,1);
 assert.deepEqual(calls[0],{name:'manage_season_lifecycle',args:{p_action:'prepare',p_season:2027,p_revision:7,p_actor:'real-admin',p_payload:{games:[{external_game_id:'official'}]}}});
});
